enableMessageNames: false

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAuthToken: 1C5F79C7-A2F0-4C07-AEEB-EC0EF9369F0C
    npmRegistryServer: "https://npm.fontawesome.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
